

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  # Database Setting
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/musinsa
    username: muser
    password: muser
