server:
  port: 8081

spring:
  application:
    name: musinsa project
  profiles:
    active: local
  hikari:
    data-source-properties:
      rewriteBatchedInserts: true
    maximum-pool-size: 5
    properties:
      hibernate:
        default_batch_fetch_size: 500
        jdbc:
          batch_size: 10
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

