

spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console
  # Database Setting
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/musinsa
    username: muser
    password: muser
  jpa:
    hibernate:
      ddl-auto: update #validate : table 검증
    properties:
      hibernate:
        show_sql: true
logging:
  level:
    root: INFO
